version: "3.8"

services:
  postgres-authorization:
    container_name: "postgres_datasource_authorization"
    image: postgres:15.1
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itmoitmo
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
  postgres-payment:
    container_name: "postgres_datasource_payment"
    image: postgres:15.1
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itmoitmo
      POSTGRES_DB: payment
    ports:
      - "5434:5432"
  postgres-chat:
    container_name: "postgres_datasource_chat"
    image: postgres:15.1
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itmoitmo
      POSTGRES_DB: chat
    ports:
      - "5435:5432"
  postgres-attachment:
    container_name: "postgres_datasource_attachment"
    image: postgres:15.1
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itmoitmo
      POSTGRES_DB: attachment
    ports:
      - "5436:5432"