spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:postgresql://localhost:5435/chat
    username: postgres
    password: itmoitmo
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:5435/chat
    user: postgres
    password: itmoitmo
    database-change-log-lock-table: database_migrations_lock
    database-change-log-table: database_migrations


server:
  port: 8089

spring.jpa.show-sql: true


eureka:
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-second: 3
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/