spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql:localhost:5434/payment
    username: postgres
    password: itmoitmo
    driver-class-name: org.postgresql.Driver
  liquibase:
    database-change-log-lock-table: database_migrations_lock
    database-change-log-table: database_migrations
server:
  port: 8088

spring.jpa.show-sql: true


eureka:
  instance:
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/