security:
  jwt:
    header: Authorization
    prefix: Bearer
    expiration: '86400'
    uri: /auth/**
    secret: JwtSecretKey
spring:
  application:
    name: core-service
  main:
    allow-circular-references: 'true'
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: itmoitmo
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
server:
  port: '8080'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
