spring:
  application:
    name: chat-service
  r2dbc:
    url: r2dbc:postgresql://localhost:49153/postgres
    username: postgres
    password: postgrespw
    properties:
      schema: public
server:
  port: '8081'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
