spring:
  application:
    name: ${APPLICATION_NAME:gateway}
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: facade-service
          uri: lb://facade-service
          predicates:
            - Path=/api/**

server:
  port: ${SERVER_PORT:8080}


eureka:
  instance:
    hostname: spring-gateway
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
