spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:postgresql://localhost:5435/chat
    username: postgres
    password: itmoitmo
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:5435/chat
    user: postgres
    password: itmoitmo
    database-change-log-lock-table: ${MIGRATIONS_TABLE_lOCK:database_migrations_lock}
    database-change-log-table: ${MIGRATIONS_TABLE:database_migrations}
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
